# Generated by Django 4.2.5 on 2023-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Api',
        ),
        migrations.DeleteModel(
            name='Cloud',
        ),
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='Others',
        ),
        migrations.DeleteModel(
            name='ProLang',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
