# Generated by Django 4.2.5 on 2023-09-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0003_project_description_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
