# Generated by Django 4.2.5 on 2023-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0006_alter_about_description_alter_contact_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='url',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='published_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
