# Generated by Django 4.2.5 on 2023-09-11 13:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0007_remove_about_url_about_image_about_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
