# Generated by Django 4.2.5 on 2023-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0010_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
