# Generated by Django 4.2.5 on 2023-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0012_alter_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
