# Generated by Django 4.2.5 on 2023-09-12 15:00

import anannosapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anannosapp', '0014_alter_portfolio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='video_file',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/', validators=[anannosapp.models.validate_file_type]),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
