# Generated by Django 4.2.5 on 2023-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0016_remove_about_file_remove_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
