# Generated by Django 4.2.5 on 2023-09-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0017_portfolio_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
    ]
