# Generated by Django 4.2.5 on 2023-09-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0018_rename_first_name_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
