# Generated by Django 4.2.5 on 2023-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anannosapp', '0019_about_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
