# Generated by Django 4.2.5 on 2023-09-21 04:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='file',
        ),
        migrations.AddField(
            model_name='blog',
            name='files',
            field=models.FileField(blank=True, help_text='Select multiple files to upload (hold down Ctrl or Shift key while selecting).', null=True, upload_to='uploads/', validators=[blog.models.validate_file_type]),
        ),
    ]
