# Generated by Django 4.2.5 on 2023-09-21 04:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_file_blog_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[blog.models.validate_file_type]),
        ),
    ]
