# Generated by Django 4.2.5 on 2023-09-21 05:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='files',
        ),
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/', validators=[blog.models.validate_file_type]),
        ),
    ]
